config/routes.rb
WdiProject1::Application.routes.draw do

  ###############################
  #####     SITE ROUTES     #####
  ###############################

  put  "/login"              => "site#login"           , :as => :login
  get  "/login_form"         => "site#user_login"      , :as => :user_login
  get  "/logout"             => "site#logout"          , :as => :logout
  get  "/account"            => "users#account"
  get  "/signup"             => "site#signup"          , :as => :signup
  

  get  "/games/list"         => "site#game_list"       , :as => :game_list
  get  "/games/:id"          => "site#game_detail"     , :as => :game_detail

  get  "/welcome"            => "site#welcome_screen"
  get  "/hello"              => "site#hello_stranger"  , :as => :hello_stranger


  ###############################
  ######   USER ROUTES   ########
  ###############################

  # get     "/users"           => "users#index"    , as: :list_users
  # get     "/users/new"       => "users#new"      , as: :users
  # post    "/users"           => "users#create"   , as: :create_user
  # get     "/users/:id"       => "users#show"     , as: :user
  # get     "/users/:id/edit"  => "users#edit"     , as: :edit_user
  # put     "/users/:id"       => "users#update"
  # delete  "/users/:id"       => "users#destroy"  , as: :destroy_user

  resources :users


  ###############################
  ######    GAME ROUTES   #######
  ###############################

  # get     "/games"           => "games#index"
  # get     "/games/new"       => "games#new"      , as: :add_game
  # post    "/games"           => "games#create"   , as: :create_game
  # get     "/games/:id"       => "games#show"     , as: :show_game
  # get     "/games/:id/edit"  => "games#edit"     , as: :edit_game
  # put     "/games/:id"       => "games#update"   , as: :update_game
  # delete  "/games/:id"       => "games#destroy"  , as: :destroy_game

  resources :games


  ###############################
  ####  GAME RATING ROUTES  #####
  ###############################

  get "/game_ratings/new"
  get "/game_ratings/create"
  get "/game_ratings/edit"
  get "/game_ratings/update"


  ###############################
  ####  GAME REVIEW ROUTES  #####
  ###############################

  get "game_reviews/new"
  get "game_reviews/create"
  get "game_reviews/show"
  get "game_reviews/edit"
  get "game_reviews/update"
  get "game_reviews/destroy"


  root :to => "site#index"

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :authorize, except: [:index, :login, :signup]

  def index
    @games = Game.all.sort
  end

  ###############################
  #####   LOGIN AND LOGOUT  #####
  ###############################

  def login
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id

      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"

      render 'index'
    end
  end

  def logout
    session[:user_id] = nil

    redirect_to root_url, :notice => "Logged out!"
  end

  def user_login
    render partial: 'login_form'
  end

  ###############################
  ####  WELCOME AND SIGNUP   ####
  ###############################

  def hello_stranger
    @user = User.new
  end

  def signup
    @user = User.new

    render :partial => 'signup_form', layout: false
  end

  def welcome_screen
    render :partial => 'welcome_screen', layout: false
  end

  ###############################
  #####    GAME METHODS     #####
  ###############################

  def game_list
    @games = Game.all.sort

    render :partial => 'game_list', layout: false
  end

  def game_detail
    @game = Game.find(params[:id])
    
    render :partial => 'game_detail', layout: false    
  end





#####################################


  # def check_for_and_add_user_steam_games

  #   results.each do |game|
  #     steam_game_id = game['appid']
      
  #     if Game.
  #     if game['appid'] != 
  #       Game.create name: game['name'], steam_game_id: game['appid']
  #     end
  #   end
  # end


  # Check games owned by user
  def check_games
    mysteam64id = "76561198054201790"

    usergames = JSON.parse(open("http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=47759AFAA400BE100A45F20F9A918C3E&steamid=" + @user.steam64id + "&format=json&include_appinfo=1&include_played_free_games=1").read)
    
    temp_user_game_v = usergames["response"]["games"]

    num_steam_games = temp_user_game_v["game_count"]

    temp_user_game_v.each do |g|
      temp_app_id = g['appid']
      temp_game_name = g['name']

      if !Game.exists?(steam_game_id: temp_app_id)
        newgame = Game.create(name: temp_game_name, steam_game_id: temp_app_id)
      end

      @user.games << newgame

    end
  end


  def check_steam_info
    p_summary = JSON.parse(open("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=47759AFAA400BE100A45F20F9A918C3E&steamids=" + @user.steam64id ).read)
    player_avatar = p_summary['response']['avatarfull']
  end

  # Set steam64id by checking vanityurl
  def check_steam_64_id
    @user.steam64id = JSON.parse(open("http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=47759AFAA400BE100A45F20F9A918C3E&vanityurl=" + @user.steamid ).read)
  end




  ###############################
  #####   ACCOUNT METHODS   #####
  ###############################

  def account_page
    @user = User.find(params[:id])

    render :partial => 'account_page', layout: false
  end

  def profile_page
    @profile = User.find(params[:id]).profile

    render :partial => 'profile_page', layout: false
  end


end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/_account_page.html.erb
<h1>My account</h1>

<div class="tabbable tabs-right">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Overview</a></li>
    <li><a href="#tab2" data-toggle="tab">Section 2</a></li>
    <li><a href="#tab3" data-toggle="tab">Settings</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <p>I'm in Section 1.</p>
    </div>
    <div class="tab-pane" id="tab2">
      <p>Blah blah blah Section 2.</p>
    </div>
    <div class="tab-pane" id="tab3">
      <p>Settings</p>
      <p>Link your steam account.</p>
      <p>What is your steam profile name?</p>
      <%= form_for(@user) do |f| %>
        <%= f.label :usersteamid %>:
        <%= f.text_field :usersteamid %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>






<h1>My account</h1>

<div class="tabbable tabs-right">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Overview</a></li>
    <li><a href="#tab2" data-toggle="tab">Profile</a></li>
    <li><a href="#tab3" data-toggle="tab">Settings</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <p>I'm in Section 1.</p>
      <p>Change email</p>
      <p>alo</p>
    </div>
    <div class="tab-pane" id="tab2">
      <div class="profile-update-form">
        <form method="put" action="/update_user_profile">
          <input type ="text"      name="display_name"     placeholder="enter your email" >
          <input type ="password"  name="password"  placeholder="enter your password"     >
          <button type ="submit"   class="btn"     >Update Profile</button>
        </form>
      </div>
    </div>
    <div class="tab-pane" id="tab3">
      <p>Settings</p>
      <p>Link your steam account.</p>
      <p>What is your steam profile name?</p>

      <p>Change your password</p>
    </div>
  </div>
</div>

app/views/site/_game_detail.html.erb
<div class="game-detail">
  <div class="game-name">
    <h2><%= @game.name %></h2>
  </div>
  <% if @game.steam_game_id %>
    <div class="game-steamid">
      <a href="http://store.steampowered.com/app/<%= @game.steam_game_id %>">Check out <%= @game.name %> on Steam!</a>
    </div>
  <% end %>
  <div class="game-description pull-right" >
    <p> <%= @game.description %> </p>
  </div>
  <div id="game_poster">
    <img src="<%= @game.poster %>" width=200px>
  </div>
  <button id="write_review_button" class="btn">Write Review</button>
  <div id="new_review" class="user-review">
  </div>
  <%= render partial: 'greviews' %>
</div>

app/views/site/_game_list.html.erb
<ul class="gamelist">
  <% @games.each do |g| %>
    <li>
      <%= link_to g.name, game_detail_path(g.id), :class => 'gamejax' %>
    </li>
  <% end %>
</ul>

app/views/site/_game_sidebar.html.erb
<div class="game-list-container" id="game_sidebar">
  <%= render :partial => 'game_list' %>
</div>

app/views/site/_greviews.html.erb
<ul class="grev-list">
  <% @game.game_reviews.each do |grev| %>
    <ul class="grev-item">
      <li class="review-reviewer-avatar">
        <img class="rounded" src="<%= grev.user.avatar_url %>" alt="">
      </li>
      <li class="review-reviewer-name">
        <%= grev.user.display_name %>
      </li>
      <li class="review-rating">  
        Rating: <%= grev.game_rating.rating %>
      </li>
      <li class="review-title">
        <%= grev.title %>
      </li>
      <li class="review-body">
        <%= grev.body %>
      </li>
    </ul>
  <% end %>
</ul>

app/views/site/_hello_stranger.html.erb
<div id="directions_to_stranger">
  <h1>Please log in</h1>
</div>
<div id="login_screen">
  <%= render partial: 'login_form' %>
</div>

app/views/site/_login_form.html.erb
<form class="centered-object login-form" accept-charset="UTF-8" method="post" action="/login">
  <input  name = "_method"   type  = "hidden"   value = "put" />
  <input  type = "text"      name  = "email"    placeholder = "yoda@alliance.io"><br>
  <input  type = "password"  name  = "password" placeholder = "thereisnotry"><br>
  <button type = "submit"    class = "btn"      >Log In</button>
</form>
<div class="centered-object">
  <p>or <a id="user_signup_link" href="/signup">create</a> an account</p>
</div>

app/views/site/_review_form.html.erb
<%= form_for(@game_reviews) do |f| %>
  <%= f.label :title%>
  <%= f.text_field %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..10) %>
  <%= f.submit %>
<% end %>

app/views/site/_signup_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email%>
  <%= f.text_field :email, placeholder: "darthvader@vader.fm" %>

  <%= f.label :display_name %>
  <%= f.text_field :display_name, placeholder: "darthvader" %>
  
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "iamyourfather"%>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "itrulyamyourfather" %><br>
  
  <%= f.submit value: "Join the Dark Side", class: "btn" %>
<% end %>

app/views/site/_welcome_screen.html.erb
<div id="main">
  <p>What is your Steam username?</p>
  <form accept-charset="UTF-8" method="post" action="/">
    <input type="text" placeholder="steamuser"></input>
    <input type="submit" class="btn" href=""></input>
  </form>
</div>

app/views/site/index.html.erb
<section role="main" id="everything">
  <% if current_user %>
    <div>
      <%= render partial: 'welcome_screen' %>
      <%= render partial: 'game_sidebar' %>
    </div>
  <% else %>
    <%= render partial: 'hello_stranger' %>
  <% end %>
</section>